
# Hier nur die zu ergänzenden Abschnitte in der "Configuration.Yaml" des spezifischen HA Systems

################################################################################################
# 1. Konfiguration der lokalen Integration der Maxxicharge Betriebsdaten (Offiziell)

template: !include z_conf_template.yaml

################################################################################################
# 2. Konfiguration für das Auslesen der Maxxicharge Konfiguration aus dem lokalen UI (Inoffiziell)

scrape: !include z_conf_scrape.yaml

################################################################################################
# 3. Konfiguration für das Ändern Maxxicharge Konfiguration mittels des lokalen UI (Inoffiziell)

